export {
  buildTriad,
  getTriadIntervals,
  getTriadInfo,
  getAlterationInterval,
  extendTriad,
  getAllIntervals,
  getExtendedChordName,
  getExtendedChordInfo,
  calculateFretboardForTriad,
  formatNoteFr,
  formatIntervalFr,
  NOTE_FR,
  COMMON_EXTENSION_PRESETS,
  type TriadQuality,
  type TriadExtension,
  type ExtensionAlteration,
  type ExtensionConfig,
  type TriadInfo,
  type ExtendedChordInfo,
  type FretboardTriadNote,
} from './triadsCalculations';
